import type { Metadata } from 'next';
import { signOut } from '@/auth';

export const metadata: Metadata = {
  title: 'Siri',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <form
        action={async () => {
          'use server';
          await signOut({ redirectTo: '/auth/login' });
        }}
      >
        <button type={'submit'}>Sign out</button>
      </form>
      {children}
    </div>
  );
}
