import { NavBar } from '@/components/auth/NavBar';
import type { Metadata } from 'next';
import { SessionProvider } from 'next-auth/react';
export const metadata: Metadata = {
  title: 'some cool name',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <SessionProvider>
    <div>
      <NavBar></NavBar>
      <div className={'grid place-items-center'}>
        <div className={'w-4/5 max-w-screen-2xl min-h-56 p-5 '}>{children}</div>
      </div>
    </div>
    // </SessionProvider>
  );
}
